name: Continuous Build Linux

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu:21.04

    steps:
      - uses: actions/checkout@v2
      - name: Install build tools
        run: |
          apt update && \
          apt install coreutils sed git build-essential gcc-11 g++-11 -y
          apt install g++-11-aarch64-linux-gnu -y
      - name: Resolve git hash
        run: |
          git init
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          mkdir multiarch_bin
      - name: Compile x86_64
        run: |
          make CXX=g++-11 ARCH=x86_64 STATIC=true QUIET=true
          mv bin/btop multiarch_bin/btop-x86_64-$GIT_HASH
          make distclean
      - name: Compile aarch64
        run: |
          make CXX=aarch64-linux-gnu-g++-11 ARCH=aarch64 STATIC=true QUIET=true
          mv bin/btop multiarch_bin/btop-aarch64-$GIT_HASH
          make distclean
      - uses: actions/upload-artifact@v2
        with:
          name: btop
          path: 'multiarch_bin/btop-*'