name: Continuous Build

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu:21.04

    steps:
      - uses: actions/checkout@v2
      - name: Install g++, make
        run: |
          apt update && \
          apt install coreutils sed git build-essential gcc-11 g++-11 -y
      - name: Build
        run: make 

      - uses: actions/upload-artifact@v2
        with:
          name: Upload built binary
          path: 'bin/btop'
