name: Continuous Build Linux

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu:21.04

    steps:
      - uses: actions/checkout@v2
      - name: Install build tools
        run: |
          apt update && \
          apt install coreutils sed git build-essential gcc-11 g++-11 -y
      - name: Compile
        run: |
          make STATIC=true
          git init
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          mv bin/btop bin/btop-$GIT_HASH

      - uses: actions/upload-artifact@v2
        with:
          name: btop
          path: 'bin/btop-*'